### ISSUE TITLE
How to properly upload QR codes?

### ISSUE THREAD

**Issue by xioren** [sn-extensions/token-vault#32]
I am trying to add my amazon account. I take a picture of the QR code and upload it but nothing happens. I have done it about 10 times now. What am I missing? I have made sure it is not blurry.

**Comment by johnny243** [comment]
Hi @xioren!

Try saving the QR code with your browser and then upload that instead. Uploading a picture from your camera does not work very well.

Let me know!

**Comment by xioren** [comment]
I'm just gonna use a different authenticator thanks.
