### ISSUE TITLE
Vertically center numbers with ... button

### ISSUE THREAD

**Issue by mobitar** [sn-extensions/token-vault#7]
From this screenshot the ... menu button is not aligned with the numbers. Should be vertically centered wrt to each other.
![60987156-ec54fe80-a338-11e9-89c6-deda626fae0f](https://user-images.githubusercontent.com/3277844/61060653-7dbb8380-a3c0-11e9-9d6f-3f8836c4e7e8.png)

**Comment by dagjaneiro** [comment]
I've adjusted the options menu to be aligned with the title:

![image](https://user-images.githubusercontent.com/10207818/61065466-a1e88600-a3fb-11e9-8967-38698d9ac5ff.png)

![image](https://user-images.githubusercontent.com/10207818/61065481-ad3bb180-a3fb-11e9-8cff-365017049295.png)
