### ISSUE TITLE
Token Vault Editor sometimes not loading on OSX when in background

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [sn-extensions/token-vault#83]
Since the last update, I very often that I have the problem that the Token Vault Editor is not loading when I open the app (desktop version) from the background / standby.

It also doesnt fix it when I click on another note and go back, it still shows only a blank white screen.

When I restart Standard Notes completely, it works fine again?

**Comment by atmoio** [comment]
We've made some fixes here in the next release. This issue is hard to diagnose as I haven't been able to figure out the necessary replication steps, although I do sometimes experience it. Hopefully some of the fixes in the next release will address this.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Works now fine, thank you so much! Really great product! ❤️
